# -*- coding: utf-8 -*-
"""MLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ew5OnCdZdu7TAEUfn4QYA8w6lrB7vfF-

# Imports and Setup
"""

# download dependencies
!pip install tensorflow numpy pandas keras

# Imports
import numpy as np

from tensorflow.keras import optimizers
from keras import models
from keras import layers
from tensorflow.keras.utils import to_categorical

from sklearn import datasets
from sklearn.model_selection import train_test_split

"""# Load Data

## Find Dataset Here: 
https://www.kaggle.com/datasets/arshid/iris-flower-dataset?select=IRIS.csv
"""

iris_dataset = datasets.load_iris()

X = iris_dataset.data
y = iris_dataset.target


for num in iris_dataset['data']:
  num *= 10

iris_dataset['data'] = iris_dataset['data'].astype(int)

iris_dataset

"""# Defining the Model"""

network = models.Sequential()
network.add(layers.Dense(3, activation='sigmoid', input_shape=(4,)))

"""# Compiling the Model"""

adam_optimizer = optimizers.Adam(learning_rate=0.1)

network.compile(optimizer=adam_optimizer,
                loss='categorical_crossentropy',
                metrics=['accuracy'])

"""# Separating Training and Testing Data"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

train_labels = to_categorical(y_train)
test_labels = to_categorical(y_test)

"""# Training the Model"""

try:
  network = models.load_model('/content/sample_data/mlp')
except:
  network.fit(X_train, train_labels, epochs=20, batch_size=1)

"""# Evaluating the Model with Test Data"""

test_loss, test_acc = network.evaluate(X_test, test_labels)

"""# Save the model"""

network.save('/content/sample_data/mlp')

for layer in network.layers: print(layer.get_weights()[0].astype(int), layer.get_weights()[1].astype(int))